In [2]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [3]:
# Project folder path
path = r'C:\Users\nanu_\Documents\Career Foundry\Projects\2 Data Immersion\Python fundamental for Data Analysis\01-2024 Instacart Basket analysis'

In [4]:
path

'C:\\Users\\nanu_\\Documents\\Career Foundry\\Projects\\2 Data Immersion\\Python fundamental for Data Analysis\\01-2024 Instacart Basket analysis'

In [5]:
# Importing ords_prods_merge Dataframe 
df_ords_prods_merge_final = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_final.pkl'))

In [6]:

df_ords_prods_merge_final.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,time_of_day,days_since_prior_order,First_Order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_modified,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Most orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,Not First Order,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,First Order,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,Not First Order,11,1,both,Mid-range product,Least busy,Slowest days,Most orders

In [7]:
# Create a subset
df_ords_prods_merge_final_1 = df_ords_prods_merge_final[:1000000]

In [8]:
df_ords_prods_merge_final_1.shape

(1000000, 19)

In [9]:
df_ords_prods_merge_final_1.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,time_of_day,days_since_prior_order,First_Order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_modified,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Most orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,Not First Order,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,First Order,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,Not First Order,11,1,both,Mid-range product,Least busy,Slowest days,Most orders
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,Not First Order,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders

# Grouping Data with Pandas

In [10]:
df_ords_prods_merge_final_1.groupby('product_name')

In [11]:
# Calculation mean of the order_number by department_id from the data frame
df_ords_prods_merge_final_1.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [12]:
## Performing a single Aggregation
df_ords_prods_merge_final_1.groupby('department_id')['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

In [13]:
# Performing Multiple Aggregation
df_ords_prods_merge_final_1.groupby('department_id').agg({'order_number': ['mean','min','max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.447411   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.803851   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

# Aggregating Data with transform()

### Create a loyalty flag using loc

In [14]:
df_ords_prods_merge_final['max_order'] = df_ords_prods_merge_final.groupby(['user_id'])['order_number']. transform(np.max)

In [15]:
df_ords_prods_merge_final.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,time_of_day,days_since_prior_order,First_Order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_modified,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Most orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,Not First Order,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,First Order,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,Not First Order,11,1,both,Mid-range product,Least busy,Slowest days,Most orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,Not First Order,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,First Order,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,Not First Order,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,Not First Order,4,1,both,Mid-range product,Regularly busy,Regular days,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,Not First Order,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13

In [16]:
df_ords_prods_merge_final.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,time_of_day,days_since_prior_order,First_Order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_modified,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Most orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,Not First Order,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,First Order,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,Not First Order,11,1,both,Mid-range product,Least busy,Slowest days,Most orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,Not First Order,8,0,both,Mid-range product,Regularly busy,Regular days,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,Not First Order,6,0,both,Mid-range product,Regularly busy,Regular days,Most orders,21

In [17]:
pd.options.display.max_rows = None

In [18]:
df_ords_prods_merge_final.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,time_of_day,days_since_prior_order,First_Order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_modified,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Most orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,Not First Order,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,First Order,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,Not First Order,11,1,both,Mid-range product,Least busy,Slowest days,Most orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,Not First Order,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,First Order,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,Not First Order,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,Not First Order,4,1,both,Mid-range product,Regularly busy,Regular days,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,Not First Order,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,Not First Order,18,1,both,Mid-range product,Regularly busy,Regular days,Average orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,Not First Order,12,1,both,Mid-range product,Regularly busy,Regular days,Average orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,Not First Order,10,0,both,Mid-range product,Regularly busy,Regular days,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,Not First Order,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,Not First Order,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,8.0,Not First Order,7,1,both,Mid-range product,Regularly busy,Regular days,Fewest orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,6.0,Not First Order,6,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,28.0,Not First Order,6,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,7.0,Not First Order,10,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,7.0,Not First Order,3,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,0.0,Not First Order,5,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,7.0,Not First Order,11,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,7.0,Not First Order,11,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,7.0,Not First Order,5,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,7.0,Not First Order,15,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,3.0,Not First Order,4,1,both,Mid-range product,Least busy,Slowest days,Average orders,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,16.0,Not First Order,6,1,both,Mid-range product,Regularly busy,Regular days,Average orders,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,5.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,6.0,Not First Order,1,1,both,Mid-range product,Busiest day,Busiest days,Average orders,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,NaN,First Order,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,4
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,21.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Regular days,Most orders,4
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,2.0,Not First Order,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,4
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,NaN,First Order,1,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,18.0,Not First Order,6,1,both,Mid-range product,Busiest day,Busiest days,Most orders,10
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,8.0,Not First Order,3,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,30.0,Not First Order,10,1,both,Mid-range product,Busiest day,Busiest days,Most orders,10
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,25.0,Not First Order,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,10
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,NaN,First Order,12,0,both,Mid-range product,Busiest day,Busiest days,Most orders,10
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,9.0,Not First Order,10,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,23
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,10.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,25
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,7.0,Not First Order,11,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,NaN,First Order,8,0,both,Mid-range product,Regularly busy,Regular days,Average orders,5
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,30.0,Not First Order,7,0,both,Mid-range product,Regularly busy,Regular days,Most orders,6
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,NaN,First Order,2,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,3
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,7.0,Not First Order,8,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,42
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,7.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,42
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,7.0,Not First Order,6,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,42
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,5.0,Not First Order,3,1,both,Mid-range product,Regularly busy,Regular days,Most orders,42
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,4.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,42
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,8.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Regular days,Average orders,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,30.0,Not First Order,2,0,both,Mid-range product,Busiest day,Busiest days,Average orders,9
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,NaN,First Order,9,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,29.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,4
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,12.0,Not First Order,7,0,both,Mid-range product,Busiest day,Busiest days,Most orders,14
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,NaN,First Order,11,0,both,Mid-range product,Least busy,Slowest days,Most orders,6
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,4.0,Not First Order,6,0,both,Mid-range product,Regularly busy,Regular days,Average orders,8
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,5.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,5.0,Not First Order,6,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,13.0,Not First Order,3,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,10.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,31
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,6.0,Not First Order,1,1,both,Mid-range product,Busiest day,Busiest days,Average orders,31
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,9.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,31
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,6.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Regular days,Most orders,31
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,8.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,31
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,1.0,Not First Order,13,0,both,Mid-range product,Least busy,Slowest days,Most orders,99
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,7.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,36
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,21.0,Not First Order,2,0,both,Mid-range product,Least busy,Slowest days,Most orders,9
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,30.0,Not First Order,2,0,both,Mid-range product,Busiest day,Busiest days,Most orders,5
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,30.0,Not First Order,1,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,5
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,NaN,First Order,11,0,both,Mid-range product,Busiest day,Busiest days,Most orders,5
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,30.0,Not First Order,3,0,both,Mid-range product,Busiest day,Busiest days,Most orders,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,8.0,Not First Order,2,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,7.0,Not First Order,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,14.0,Not First Order,2,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,28.0,Not First Order,1,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,16.0,Not First Order,4,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,1.0,Not First Order,1,1,both,Mid-range product,Least busy,Slowest days,Average orders,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,14.0,Not First Order,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,7.0,Not First Order,2,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,8.0,Not First Order,1,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,16.0,Not First Order,7,1,both,Mid-range product,Least busy,Slowest days,Most orders,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,8.0,Not First Order,16,0,both,Mid-range product,Least busy,Slowest days,Average orders,23
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,14.0,Not First Order,5,0,both,Mid-range product,Least busy,Slowest days,Average orders,11
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,NaN,First Order,2,0,both,Mid-range product,Busiest day,Busiest days,Most orders,5
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,8.0,Not First Order,8,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,14.0,Not First Order,15,0,both,Mid-range product,Regularly busy,Regular days,Most orders,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,14.0,Not First Order,9,1,both,Mid-range product,Regularly busy,Regular days,Most orders,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,10.0,Not First Order,1,0,both,Mid-range product,Busiest day,Busiest days,Average orders,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,14.0,Not First Order,4,1,both,Mid-range product,Busiest day,Busiest days,Average orders,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,4.0,Not First Order,2,1,both,Mid-range product,Regularly busy,Regular days,Most orders,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,Not First Order,5,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,Not First Order,1,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,Not First Order,8,0,both,Mid-range product,Regularly busy,Regular days,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,Not First Order,2,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,Not First Order,6,0,both,Mid-range product,Regularly busy,Regular days,Most orders,21

In [19]:
'df_ords_prods_merge_final.loc[df_ords_prods_merge_final['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer''

In [20]:
df_ords_prods_merge_final.loc[(df_ords_prods_merge_final['max_order'] <= 40) & (df_ords_prods_merge_final['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [21]:
df_ords_prods_merge_final.loc[df_ords_prods_merge_final['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [22]:
# Counting the value max_order
df_ords_prods_merge_final['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [23]:
# Checking the result of max_order column
df_ords_prods_merge_final['max_order'].head(50)

0     32
1     32
2      5
3      3
4      3
5     26
6      9
7     12
8     20
9     20
10    10
11    43
12    43
13    43
14    13
15    13
16    13
17    28
18    28
19    28
20    28
21    28
22    28
23    28
24    28
25    28
26    28
27    28
28    28
29    28
30    28
31    28
32    28
33    28
34     4
35     4
36     4
37    10
38    10
39    10
40    10
41    10
42    10
43    23
44    25
45    13
46     5
47     6
48     3
49    42
Name: max_order, dtype: int64

In [24]:
df_ords_prods_merge_final.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,time_of_day,...,First_Order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_modified,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Not First Order,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Not First Order,1,1,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Not First Order,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,First Order,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Not First Order,11,1,both,Mid-range product,Least busy,Slowest days,Most orders,3,New customer

In [25]:
df_ords_prods_merge_final[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010  Regular customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006    Loyal customer             2
50     4006    Loyal customer             3
51     4006    Loyal customer             5
52     4006    Loyal customer             9
53     4006    Loyal customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845  Regular customer             6
59     6866      New customer             1